#!/bin/bash

#uncomment the your choice
#save file
#chmod +x sup
#sudo mv /path/to/sup /bin/sup
#In terminal just type sup

#Ubuntu
#sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo snap refresh
#Ubuntu + Flatpak
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo snap refresh && && flatpak uninstall --unused -y && flatpak update -y 
#APT Only
#sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
#APT + Flatpak
#sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && flatpak uninstall --unused -y && flatpak update -y
